name: build action
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: build
        run: cmake -B ${{github.workspace}}/build && cmake --build ${{github.workspace}}/build
      - name: test
        run: |
            ctest --test-dir ${{github.workspace}}/build --rerun-failed --output-on-failure
      - name: valgrind
        run: |
            sudo apt-get install -y valgrind
            valgrind --tool=memcheck -v --leak-check=full --show-leak-kinds=all ${{github.workspace}}/build/tests/lock_free_test1

