name: build action
on: [push]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: build
        run: cmake -B ${{github.workspace}}/build && cmake --build ${{github.workspace}}/build
      - name: test
        run: |
            ctest --test-dir ${{github.workspace}}/build --rerun-failed --output-on-failure
            #valgrind --tool=memcheck ./${{github.workspace}}/build/test/lock_free_test1

